{
 "title": "Contrast",
 "time": { "from": "now-45m", "to": "now" },
 "panels": [
  {
   "title": "Attack results",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(result) (rate({result=~\".+\"} | json [$__auto]))"
    }
   ]
  },
  {
   "title": "Service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(service) (rate({result=~\".+\"} | json [$__auto]))"
    }
   ]
  },
  {
   "title": "Language",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(application_agentLanguage) (rate({result=~\".+\"} | json [$__auto]))"
    }
   ]
  },
  {
   "title": "Attack results",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(result) (rate({result=~\".+\"} | json [$__auto]))"
    }
   ]
  }
 ]
}